name: GitHub Actions Demo
run-name: Testing out GitHub Actions on: [push]

on: 
  push:

jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Print Job Message
        run: echo "Job is executing as part of Basic workflow"
