name: GitHub Actions Demo

on: 
  push:

jobs:
  Basic-Workflow:
    name: Testing out GitHub Actions on Push
    runs-on: ubuntu-latest

    steps:
      - name: Print Job Message
        run: echo "Job is executing as part of Basic workflow"
